site:
  title: "Code FREAK Docs"
  url: https://docs.codefreak.org
  start_page: codefreak::index.adoc
  robots: allow
content:
  sources:
  - url: https://github.com/codefreak/codefreak.git
    # If you include more branches make sure you set the docs/antora.yml file "version" attribute to a distinct value.
    # Otherwise, the build will fail with a message like "error: Duplicate nav: master@codefreak:ROOT:nav.adoc"
    branches:
      - master
      - v6
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public
