site:
  title: "Code FREAK Docs"
  url: https://docs.codefreak.org
  start_page: codefreak::index.adoc
  robots: allow
content:
  sources:
  - url: https://github.com/code-freak/code-freak.git
    branches: master
    start_path: docs
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./public

