name: Build Docker Image

on: [push, pull_request, release]

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build Docker image
        run: |
          docker build -t cfreak/homepage-docs:latest .

      - name: Before Deploy
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        run: |
          docker logout
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Deploy master branch as latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker push cfreak/homepage-docs:latest
